/* cable recipes for ae2 because i'm so tired of having to use the spray cans....*/
ServerEvents.recipes(event =>  {
    const cables = ["smart","glass","covered"]
    const big_cables = ["smart_dense","covered_dense"]
    const colors = ["black", "blue", "brown", "cyan", "gray", "green", "light_blue", "light_gray", "lime", "magenta", "orange", "pink", "purple", "red", "white", "yellow"]
    colors.forEach(color => {
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/fluix_covered_cable_dye_${color}`)
            .itemInputs("#ae2:covered_cable")
            .inputFluids(`gtceu:${color}_dye 8`)
            .itemOutputs(`ae2:${color}_covered_cable`)
            .duration(20)
            .EUt(8)
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/fluix_smart_cable_dye_${color}`)
            .itemInputs("#ae2:smart_cable")
            .inputFluids(`gtceu:${color}_dye 8`)
            .itemOutputs(`ae2:${color}_smart_cable`)
            .duration(20)
            .EUt(8)
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/fluix_covered_dense_cable_dye_${color}`)
            .itemInputs("#ae2:covered_dense_cable")
            .inputFluids(`gtceu:${color}_dye 32`)
            .itemOutputs(`ae2:${color}_covered_dense_cable`)
            .duration(20)
            .EUt(8)
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/fluix_smart_dense_cable_dye_${color}`)
            .itemInputs("#ae2:smart_dense_cable")
            .inputFluids(`gtceu:${color}_dye 32`)
            .itemOutputs(`ae2:${color}_smart_dense_cable`)
            .duration(20)
            .EUt(8)
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/fluix_glass_cable_dye_${color}`)
            .itemInputs("#ae2:glass_cable")
            .inputFluids(`gtceu:${color}_dye 8`)
            .itemOutputs(`ae2:${color}_glass_cable`)
            .duration(20)
            .EUt(8)
    })
    cables.forEach(type => {
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/colored_cable_wash_${type}_water`)
            .itemInputs(`#ae2:${type}_cable`)
            .inputFluids(`minecraft:water 8`)
            .itemOutputs(`ae2:fluix_${type}_cable`)
            .duration(20)
            .EUt(8)
    })
    big_cables.forEach(type => {
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/colored_cable_wash_${type}_water`)
            .itemInputs(`#ae2:${type}_cable`)
            .inputFluids(`minecraft:water 32`)
            .itemOutputs(`ae2:fluix_${type}_cable`)
            .duration(20)
            .EUt(8)

    })
    cables.forEach(type => {
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/colored_cable_wash_${type}_acetone`)
            .itemInputs(`#ae2:${type}_cable`)
            .inputFluids(`gtceu:acetone 1`)
            .itemOutputs(`ae2:fluix_${type}_cable`)
            .duration(20)
            .EUt(8)
    })
    big_cables.forEach(type => {
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/colored_cable_wash_${type}_acetone`)
            .itemInputs(`#ae2:${type}_cable`)
            .inputFluids(`gtceu:acetone 4`)
            .itemOutputs(`ae2:fluix_${type}_cable`)
            .duration(20)
            .EUt(8)
    })
    cables.forEach(type => {
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/colored_cable_wash_${type}_distilled_water`)
            .itemInputs(`#ae2:${type}_cable`)
            .inputFluids(`gtceu:distilled_water 8`)
            .itemOutputs(`ae2:fluix_${type}_cable`)
            .duration(20)
            .EUt(8)
    })
    big_cables.forEach(type => {
        event.recipes.gtceu.chemical_bath(`kubejs:ae2/colored_cable_wash_${type}_distilled_water`)
            .itemInputs(`#ae2:${type}_cable`)
            .inputFluids(`gtceu:distilled_water 32`)
            .itemOutputs(`ae2:fluix_${type}_cable`)
            .duration(20)
            .EUt(8)
    })
})