ServerEvents.recipes(event =>  {
    event.recipes.gtceu.mixer("pink_dye_mixing")
        .inputFluids("gtceu:red_dye 144", "gtceu:white_dye 144")
        .outputFluids("gtceu:pink_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("magenta_dye_mixing")
        .inputFluids("gtceu:purple_dye 144", "gtceu:pink_dye 144", )
        .outputFluids("gtceu:magenta_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("purple_dye_mixing")
        .inputFluids("gtceu:red_dye 144", "gtceu:blue_dye 144")
        .outputFluids("gtceu:purple_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("light_blue_dye_mixing")
        .inputFluids("gtceu:white_dye 144", "gtceu:blue_dye 144")
        .outputFluids("gtceu:light_blue_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("cyan_dye_mixing")
        .inputFluids("gtceu:blue_dye 144", "gtceu:green_dye 144")
        .outputFluids("gtceu:cyan_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("lime_dye_mixing")
        .inputFluids("gtceu:white_dye 144", "gtceu:green_dye 144")
        .outputFluids("gtceu:lime_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("orange_dye_mixing")
        .inputFluids("gtceu:red_dye 144", "gtceu:yellow_dye 144")
        .outputFluids("gtceu:orange_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("gray_dye_mixing")
        .inputFluids("gtceu:white_dye 144", "gtceu:black_dye 144")
        .outputFluids("gtceu:gray_dye 288")
        .duration(20)
        .EUt(8)
    event.recipes.gtceu.mixer("light_gray_dye_mixing")
        .inputFluids("gtceu:white_dye 144", "gtceu:gray_dye 144")
        .outputFluids("gtceu:light_gray_dye 288")
        .duration(20)
        .EUt(8)
})